name: Build Release Binaries

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Release Binaries
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Copy files to build directory
        run: |
          mkdir -p build
          cp go.mod ./build
          cp go.sum ./build
          cp -R ./cmd/main.go ./build/cmd/main.go
          cp -R ./internal/* ./build/internal

      - name: Install dependencies
        run: |
          cd build
          go mod download
          go mod tidy

      - name: Build Binary
        run: |
          cd build
          go build -ldflags "-w -s" -o ./littlelinks-generator cmd/main.go

      - name: Upload Release Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: release
          path: ./build/littlelinks-generator
