name: Build Release Binaries

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Build Release Binaries
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22

      - name: Copy files to build directory
        run: |
          mkdir -p build/cmd
          mkdir -p build/internal
          cp go.mod ./build
          cp go.sum ./build
          cp ./cmd/main.go ./build/cmd/
          cp -R ./internal/* ./build/internal/
          
      - name: Install dependencies
        run: |
          cd build
          go mod download
          go mod tidy

      - name: Build Binary
        run: |
          cd ./build
          go build -ldflags "-w -s" -o ./littlelinks-generator cmd/main.go

      - name: Upload Release Artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: ./build/littlelinks-generator
          tag_name: ${{ github.ref }}
          append_body: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
