name: Release Go project

on:
  push:
    tags:
      - "v*.*.*" # triggers only if push new tag version, like `0.8.4` or else

permissions:
    contents: write
    packages: write

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: linux/386, linux/amd64, linux/arm64, windows/386, windows/amd64, darwin/amd64, darwin/arm64
        goos: [linux]
        goarch: [amd64]
    steps:
    - uses: actions/checkout@v4
    - uses: wangyoucao577/go-release-action@v1.48
      with:
        github_token: ${{ secrets.GO_RELEASER_GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: "https://dl.google.com/go/go1.13.1.linux-amd64.tar.gz"
        project_path: "."
        binary_name: "littlelinks-generator"