name: Release Build

on:
  push:
    tags:
      - "v*.*.*"
    paths:
      - .github/workflows/build.yml
      - cmd/**
      - internal/**
      - go.mod
      - go.sum

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22'

      - name: Build
        run: go build -ldflags "-w -s" -o littlelinks-generator

      - name: Zip build artifacts
        run: |
          zip -r littlelinks-generator.zip littlelinks-generator

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: littlelinks-generator
          path: littlelinks-generator.zip
